GPU: '0'
b1: 0.5
b2: 0.999
batch_size: 1
datasets_folder: ZF-ref-local
datasets_path: /home/bbnclxy/extdisk/DeepCAD-Pro-v2/datasets
fmap: 16
gap_t: 27
gap_x: 75
gap_y: 75
lr: 5.0e-05
n_epochs: 20
output_dir: ./results
patch_t: 150
patch_x: 150
patch_y: 150
pth_path: pth
scale_factor: 1
select_img_num: 1000000
train_datasets_size: 6000
